# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/bigtony/school-resources/Northeastern University/High-Performance-Computing/homework/HW2/philosophers-dinning"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/bigtony/school-resources/Northeastern University/High-Performance-Computing/homework/HW2/philosophers-dinning"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/bigtony/school-resources/Northeastern University/High-Performance-Computing/homework/HW2/philosophers-dinning/CMakeFiles" "/Users/bigtony/school-resources/Northeastern University/High-Performance-Computing/homework/HW2/philosophers-dinning/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/bigtony/school-resources/Northeastern University/High-Performance-Computing/homework/HW2/philosophers-dinning/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named philosophers_dinning

# Build rule for target.
philosophers_dinning: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 philosophers_dinning
.PHONY : philosophers_dinning

# fast build rule for target.
philosophers_dinning/fast:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/build
.PHONY : philosophers_dinning/fast

src/fork.o: src/fork.cpp.o

.PHONY : src/fork.o

# target to build an object file
src/fork.cpp.o:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/fork.cpp.o
.PHONY : src/fork.cpp.o

src/fork.i: src/fork.cpp.i

.PHONY : src/fork.i

# target to preprocess a source file
src/fork.cpp.i:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/fork.cpp.i
.PHONY : src/fork.cpp.i

src/fork.s: src/fork.cpp.s

.PHONY : src/fork.s

# target to generate assembly for a file
src/fork.cpp.s:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/fork.cpp.s
.PHONY : src/fork.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/philosopher.o: src/philosopher.cpp.o

.PHONY : src/philosopher.o

# target to build an object file
src/philosopher.cpp.o:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/philosopher.cpp.o
.PHONY : src/philosopher.cpp.o

src/philosopher.i: src/philosopher.cpp.i

.PHONY : src/philosopher.i

# target to preprocess a source file
src/philosopher.cpp.i:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/philosopher.cpp.i
.PHONY : src/philosopher.cpp.i

src/philosopher.s: src/philosopher.cpp.s

.PHONY : src/philosopher.s

# target to generate assembly for a file
src/philosopher.cpp.s:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/philosopher.cpp.s
.PHONY : src/philosopher.cpp.s

src/topic.o: src/topic.cpp.o

.PHONY : src/topic.o

# target to build an object file
src/topic.cpp.o:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/topic.cpp.o
.PHONY : src/topic.cpp.o

src/topic.i: src/topic.cpp.i

.PHONY : src/topic.i

# target to preprocess a source file
src/topic.cpp.i:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/topic.cpp.i
.PHONY : src/topic.cpp.i

src/topic.s: src/topic.cpp.s

.PHONY : src/topic.s

# target to generate assembly for a file
src/topic.cpp.s:
	$(MAKE) -f CMakeFiles/philosophers_dinning.dir/build.make CMakeFiles/philosophers_dinning.dir/src/topic.cpp.s
.PHONY : src/topic.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... philosophers_dinning"
	@echo "... src/fork.o"
	@echo "... src/fork.i"
	@echo "... src/fork.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/philosopher.o"
	@echo "... src/philosopher.i"
	@echo "... src/philosopher.s"
	@echo "... src/topic.o"
	@echo "... src/topic.i"
	@echo "... src/topic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

